### ISSUE TITLE
Tests failing due to outdated `chefdk` on Jenkins slave

### ISSUE THREAD

**Issue by fishnix** [NorthPage/telegraf-cookbook#61]
Looks like tests are failing due to outdated chefdk on the jenkins slave:

```
  1) telegraf::default on Windows 2012r2 converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Fauxhai::Exception::InvalidPlatform: Could not find platform 'windows/2012r2' in any of the sources!> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:33:in `new'
         # ./spec/unit/recipes/default_spec.rb:33:in `block (5 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:38:in `block (6 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:38:in `block (5 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:38:in `block (5 levels) in <top (required)>'
```

**Comment by Plork** [comment]
this isn't something the cookbook can fix is it? 

2012r2 support was added somewhere in April 2014.

**Comment by fishnix** [comment]
no it's not.  the chefdk on the jenkins slave needs to be updated or we should move this off of that environment.  i just wanted to make sure folks knew it was a problem.  currently, i run tests locally before merging.

**Comment by Plork** [comment]
why not integrate appveyor and/or travis in this repo?
